fixed provisionals. It is now confirmed copying and outputting an update.zip (although unflashed.)

diff --git a/auto_patcher b/auto_patcher
--- a/auto_patcher
+++ b/auto_patcher
@@ -524,12 +524,12 @@ else
 				printtask "!!! PATCHING FAILED FOR ${FAILS[@]} !!!"
 				askconsent || printerror "failed $NAME.patch"
 				echo "### replacing ${FAILS[@]} from patches/$P/common/${FILE} ###" > ${JAR}.log
-				java -jar baksmali.jar -b -a 15 -o cmp/${FILE}.out/smali patches/$P/common/${FILE} >> $LOG 2>> $LOG || echo "FAILED to baksmali $FILE" >> ${JAR}.log
+				#java -jar baksmali.jar -b -a 15 -o tmp/${FILE}.out/smali patches/$P/common/provisionals/${FAIL} >> $LOG 2>> $LOG || echo "FAILED to baksmali $FILE" >> ${JAR}.log
 				for FAIL in ${FAILS[@]}; do
 					(contains $FAIL ${SID[@]}) && printerror "$FAIL was already replaced before"
 					printtask "... replace $FAIL ..."
 					\rm -rf tmp/${FILE}.out/smali/${FAIL}
-					\cp -a  cmp/${FILE}.out/smali/${FAIL} tmp/${FILE}.out/smali/${FAIL} || echo "FAILED to cp $FAIL" >> ${JAR}.log
+					\cp -a  patches/$PID/common/provisionals/$FILE.out/${FAIL} tmp/${FILE}.out/smali/${FAIL} || echo "FAILED to cp $FAIL" >> ${JAR}.log
 					SID=(${SID[@]} $FAIL)
 				done
 			fi
