fix substitute failed smali logic

diff --git a/auto_patcher b/auto_patcher
--- a/auto_patcher
+++ b/auto_patcher
@@ -106,82 +106,45 @@ printerror () {
 	echo "!!! error:" $1
 	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
 	echo ""	
-	if grep -w '$RIP\|pdroid' $LOG; then
-		if grep "FAILED" $LOG | grep ".jar" $LOG; then
-			trycopy
-		fi
-	else
-		debug
-	fi
+	debug
 }
-trycopy () {
-		echo ""
-		echo "These are the files for which patching failed:"
-		echo "---------------------------------------------"
-		echo ""
-		grep "FAILED" $LOG | sed -e 's/.*.\///'
-		echo ""
-		echo "---------------------------------------------"
-		sleep 1		
-		echo "Did the patcher fail to patch" 
-		echo "	ONLY"
-		echo "ActivityManagerService.smali "
-		echo "and/or ContentResolver.smali? [yes or no]"
-		read NEWCOPY
-		case $NEWCOPY in
-			[Yy] | [Yy][Ee][Ss] )
+
+askconsent () {
+	echo ""
+	echo "These are the files for which patching failed:"
+	echo "---------------------------------------------"
+	echo ""
+	echo "${FAILS[@]}"
+	echo ""
+	echo "---------------------------------------------"
+	echo ""
+	echo "We can try to add a premade copy of those files."
+	echo "This sometimes works."
+	echo ""
+	echo "But IT MAY NOT WORK!!!"
+	echo ""
+	echo ""
+	sleep 1
+	echo -n "Do you want to proceed ? (YES/no) "
+	read PROCEED
+	case $PROCEED in
+		YES)
 			echo ""
-			echo "We can try to add a premade copy of either of those files. This sometimes works. But IT MAY NOT!!!"
-			echo ""
-			echo "Select from the following options [1-4]:"
-			echo ""
-			echo "1) Replace ActivityManagerService.smali"
-			echo "2) Replace ContentResolver.smali"
-			echo "3) Replace Both"
-			echo "4) Neither. Exit"
-			echo ""
-				read ADDFILE
-				case $ADDFILE in 
-					1)
-					\rm -rf tmp/system/framework/*.out
-					decompilejar
-					mv -fv patches/$P/common/provisionals/ActivityManagerService.smali tmp/system/framework/services.jar.out/smali/com/android/server/am/
-					;;
-					2)
-					\rm -rf tmp/system/framework/*.out
-					decompilejar
-					echo "...moving provisional file..."
-					mv -fv patches/$P/common/provisionals/ContentResolver.smali tmp/system/framework/framework.jar.out/smali/android/content/
-					;;
-					3)
-					\rm -rf tmp/system/framework/*.out
-					decompilejar
-					echo "...moving provisional files..."
-					mv -fv patches/$P/common/provisionals/ContentResolver.smali tmp/system/framework/framework.jar.out/smali/android/content/
-					mv -fv patches/$P/common/provisionals/ActivityManagerService.smali tmp/system/framework/services.jar.out/smali/com/android/server/am/
-					;;
-					4)
-					debug
-					;;
-					*)
-					echo ""
-					echo "Invalid input. Please select option 1-4 by entering the integer (i.e. 4)"
-					sleep 1
-					trycopy
-					;;
-				esac
-			jarpatch
 			;;
-			[Nn] | [Nn][Oo])	
-			debug 
+		*)
+			return 1;	# error
 			;;
-			*)
-			echo ""
-			echo "!!! Invalid input. Please type 'yes' or 'no'!!!"
-			sleep 1
-			trycopy
+	esac
+	echo -n "Are you sure ? (YES/no) "
+	read PROCEED
+	case $PROCEED in
+		YES)
+			return 0;	# successful
 			;;
-		esac
+		*)
+			return 1;	# error
+			;;
+	esac
 }
 
 debug () {
@@ -193,6 +156,8 @@ debug () {
 	[ -d $TEMP ] && \rm -rf $TEMP
 	printusage
 }
+
+contains () { for e in "${@:2}"; do [[ "$e" = "$1" ]] && return 0; done; return 1; }
 
 parse () {
 	echo ${1%%_*}
@@ -300,50 +265,6 @@ extpath () {
 	esac
 }
 
-jarpatch () {
-	echo "### jar patch $P/$R/$B ###"
-		JARS=
-		[ -f patches/$P/files.txt ] && JARS=`grep .jar patches/$P/files.txt`
-		[ -f patches/$P/$R/files.txt ] && JARS=`grep .jar patches/$P/$R/files.txt`
-		for FILE in ${JARS[@]}; do
-			JAR=${FILE##*/}
-			NAME=${JAR%.jar}
-			printtask "### apply $NAME.patch ###"
-			case "$NAME" in
-			framework)
-				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log 
-				cat ${JAR}.log | tee -a $LOG
-				# patch preloaded-classes only if a patch exists
-				if [ -f $PRB/preloaded.patch ]; then
-					printtask "... apply preloaded.patch ..."
-					patch -Nls -p1 < $PRB/preloaded.patch 2>&1 > preloaded.log 
-					cat preloaded.log | tee -a $LOG
-					[[ `grep FAILED preloaded.log` != "" ]] && printerror "failed preloaded.patch"
-				fi
-				;;
-			*)
-				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log 
-				cat ${JAR}.log | tee -a $LOG
-				;;
-			esac
-			[[ `grep FAILED ${JAR}.log` != "" ]] &&  printerror "failed $NAME.patch"
-			GARBAGE=`find tmp/${FILE}.out -name "*.orig"` && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
-			GARBAGE=`find tmp/${FILE}.out -name "*.rej"`  && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
-		done
-}
-
-decompilejar () {
-# decompile system files
-	for FILE in ${JID[@]}; do
-		JAR=${FILE##*/}
-		printtask "### decompile $JAR ###"
-		java -jar baksmali.jar -b -a 15 -o tmp/${FILE}.out/smali ${FILE} >> $LOG 2>> $LOG
-		if [ $FILE == "system/framework/framework.jar" ]; then
-			printtask "... extract preloaded-classes ..."
-			jar -xvf ${FILE} preloaded-classes >> $LOG 2>> $LOG
-		fi
-	done
-}
 [[ $# -lt 1 || $1 == "-h" || -z $1 ]] && printusage
 
 ROOT=$(abspath "`dirname $0`")
@@ -570,35 +491,49 @@ else
 		done
 
 		echo "### jar patch $P/$R/$B ###"
-		jarpatch
-#		JARS=
-#		[ -f patches/$P/files.txt ] && JARS=`grep .jar patches/$P/files.txt`
-#		[ -f patches/$P/$R/files.txt ] && JARS=`grep .jar patches/$P/$R/files.txt`
-#		for FILE in ${JARS[@]}; do
-#			JAR=${FILE##*/}
-#			NAME=${JAR%.jar}
-#			printtask "### apply $NAME.patch ###"
-#			case "$NAME" in
-#			framework)
-#				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log 
-#				cat ${JAR}.log | tee -a $LOG
-#				# patch preloaded-classes only if a patch exists
-#				if [ -f $PRB/preloaded.patch ]; then
-#					printtask "... apply preloaded.patch ..."
-#					patch -Nls -p1 < $PRB/preloaded.patch 2>&1 > preloaded.log 
-#					cat preloaded.log | tee -a $LOG
-#					[[ `grep FAILED preloaded.log` != "" ]] && printerror "failed preloaded.patch"
-#				fi
-#				;;
-#			*)
-#				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log 
-#				cat ${JAR}.log | tee -a $LOG
-#				;;
-#			esac
-#			[[ `grep FAILED ${JAR}.log` != "" ]] &&  printerror "failed $NAME.patch"
-#			GARBAGE=`find tmp/${FILE}.out -name "*.orig"` && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
-#			GARBAGE=`find tmp/${FILE}.out -name "*.rej"`  && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
-#		done
+		JARS=
+		[ -f patches/$P/files.txt ] && JARS=`grep .jar patches/$P/files.txt`
+		[ -f patches/$P/$R/files.txt ] && JARS=`grep .jar patches/$P/$R/files.txt`
+		for FILE in ${JARS[@]}; do
+			JAR=${FILE##*/}
+			NAME=${JAR%.jar}
+			printtask "### apply $NAME.patch ###"
+			case "$NAME" in
+			framework)
+				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log
+				cat ${JAR}.log | tee -a $LOG
+				# patch preloaded-classes only if a patch exists
+				if [ -f $PRB/preloaded.patch ]; then
+					printtask "... apply preloaded.patch ..."
+					patch -Nls -p1 < $PRB/preloaded.patch 2>&1 > preloaded.log
+					cat preloaded.log | tee -a $LOG
+					[[ `grep FAILED preloaded.log` != "" ]] && printerror "failed preloaded.patch"
+				fi
+				;;
+			*)
+				patch -Nls -p1 -d tmp/${FILE}.out < $PRB/${NAME}.patch 2>&1 > ${JAR}.log
+				cat ${JAR}.log | tee -a $LOG
+				;;
+			esac
+			# substitute failed smali with premade jar
+			FAILS=(`grep FAILED ${JAR}.log | sed -e 's/.*smali\///' | sed -e 's/\.rej//'`)
+			if [[ -n ${FAILS[@]} ]]; then
+				printtask "!!! PATCHING FAILED FOR ${FAILS[@]} !!!"
+				askconsent || printerror "failed $NAME.patch"
+				echo "### replacing ${FAILS[@]} from patches/$P/common/${FILE} ###" > ${JAR}.log
+				java -jar baksmali.jar -b -a 15 -o cmp/${FILE}.out/smali patches/$P/common/${FILE} >> $LOG 2>> $LOG || echo "FAILED to baksmali $FILE" >> ${JAR}.log
+				for FAIL in ${FAILS[@]}; do
+					(contains $FAIL ${SID[@]}) && printerror "$FAIL was already replaced before"
+					printtask "... replace $FAIL ..."
+					\rm -rf tmp/${FILE}.out/smali/${FAIL}
+					\cp -a  cmp/${FILE}.out/smali/${FAIL} tmp/${FILE}.out/smali/${FAIL} || echo "FAILED to cp $FAIL" >> ${JAR}.log
+					SID=(${SID[@]} $FAIL)
+				done
+			fi
+			[[ `grep FAILED ${JAR}.log` != "" ]] &&  printerror "failed $NAME.patch"
+			GARBAGE=`find tmp/${FILE}.out -name "*.orig"` && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
+			GARBAGE=`find tmp/${FILE}.out -name "*.rej"`  && rm -rf $GARBAGE && echo "GARBAGE=" $GARBAGE >> $LOG
+		done
 
 
 		echo "### apk patch $P/$R/$B ###"
